### ISSUE TITLE
Crashes on RN 0.62.2

### ISSUE THREAD

**Issue by rizwanatta** [rafaelmotta/react-native-scl-alert#12]
i installed via yarn
 used it as a component and it just crashes the whole app for no reason!
```
import React from 'react';

import {SCLAlert, SCLAlertButton} from 'react-native-scl-alert';

export const WMGAlert = (props) => {
  return (
    <SCLAlert
      theme="info"
      show={props.show}
      title="Lorem"
      useNativeDriver
      subtitle="Lorem ipsum dolor">
      <SCLAlertButton theme="info" onPress={props.handleClose}>
        Done
      </SCLAlertButton>
    </SCLAlert>
  );
};

```

this error/warning comes up in flipper and app freezes then crashes

`Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false` 
SCLAlert@http://localhost:8081/node_modules/react-native-scl-alert/src/components/SCLAlert.bundle?platform=ios&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true:55:36
WMGAlert@http://localhost:8081/src/services/WMGAlert.bundle?platform=ios&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true:31:21
RCTView
RCTScrollContentView
RCTScrollView
ScrollView@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:63010:36
Settings@http://localhost:8081/src/scenes/Settings/Settings.bundle?platform=ios&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true:47:47
ConnectFunction@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:109409:43
StaticContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:161868:17
EnsureSingleNavigator@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:160542:24
SceneView@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:161746:22
RCTView
RCTView
RCTView
CardSheet@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:169424:23
RCTView
AnimatedComponent@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:62289:24
AnimatedComponentWrapper
PanGestureHandler@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:105532:38
PanGestureHandler@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:166315:34
RCTView
AnimatedComponent@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:62289:24
AnimatedComponentWrapper
RCTView
Card@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:168898:36
CardContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:168621:22
RCTView
MaybeScreen@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:166975:24
RCTView
MaybeScreenContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:166948:23
CardStack@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:166516:36
KeyboardManager@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:169593:36
RNCSafeAreaView
SafeAreaProvider@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:166174:24
SafeAreaProviderCompat@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:170053:24
RCTView
StackView@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:165734:36
StackNavigator@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:165611:32
EnsureSingleNavigator@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:160542:24
BaseNavigationContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:160308:28
ThemeProvider@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:164048:21
NavigationContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:163967:26
SceneNavigator@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158622:21
PersistGate@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:108204:22
ThemeProvider@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:128013:36
Provider@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:108997:21
App@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:107940:41
RCTView
RCTView
AppContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:68960:22`

what did I try:

1.  reverted to 1.2.0 version still crash
2. added the  animated and native driver prop result none

any help will be appreciated

**Comment by MattyK14** [comment]
I'm finding some of my modals crash, but not all. And I can't distinguish what the difference is

**Comment by MattyK14** [comment]
@rizwanatta did you have a resolution for this?
